export const trans = {
    mounted(){
        // translations
        this.trans = {
            __title: this.__('customFields.title'),
            __create: this.__('customFields.create'),
            __update: this.__('customFields.update'),
            __createFormTitle: this.__('customFields.createFormTitle'),
            __createFormRulesTitle: this.__('customFields.createFormRulesTitle'),
            __rulesUnderTitle: this.__('customFields.rulesUnderTitle'),
            __frontEndSlugExp: this.__('customFields.frontEndSlugExp'),
            __formTitle: this.__('customFields.form.title'),
            __formDescription: this.__('customFields.form.description'),
            __none: this.__('customFields.form.belongsValues.none'),
            __pages: this.__('customFields.form.belongsValues.pages'),
            __customFieldsTitle: this.__('customFields.form.customFieldsTitle'),
            __type: this.__('customFields.form.type'),
            __newFieldBtn: this.__('customFields.form.newFieldBtn'),
            __fieldName: this.__('customFields.form.fieldName'),
            __fieldKey: this.__('customFields.form.key'),
            __fieldNote: this.__('customFields.form.note'),
            __placeholder: this.__('customFields.form.placeholder'),
            __defaultValue: this.__('customFields.form.defaultValue'),
            __wrapperStyle: this.__('customFields.form.wrapperStyle'),
            __fieldStyle: this.__('customFields.form.fieldStyle'),
            __layout: this.__('customFields.form.layout'),
            __inputType: this.__('customFields.form.inputType'),
            __isActive: this.__('customFields.form.isActive'),
            __translatable: this.__('customFields.form.translatable'),
            __required: this.__('customFields.form.required'),
            __options: this.__('customFields.form.options'),
            __table: this.__('customFields.form.table'),
            __isMultiple: this.__('customFields.form.isMultiple'),
            __characterLimit: this.__('customFields.form.characterLimit'),
            __rows: this.__('customFields.form.rows'),
            __allowHTML: this.__('customFields.form.allowHTML'),
            __allowParagraphs: this.__('customFields.form.allowParagraphs'),
            __toolbar: this.__('customFields.form.toolbar'),
            __maxUploadSize: this.__('customFields.form.maxUploadSize'),
            __minWidth: this.__('customFields.form.minWidth'),
            __minHeight: this.__('customFields.form.minHeight'),
            __maxWidth: this.__('customFields.form.maxWidth'),
            __maxHeight: this.__('customFields.form.maxHeight'),
            __siblingRulesTitle: this.__('customFields.form.siblingRulesTitle'),
            __min: this.__('customFields.form.min'),
            __max: this.__('customFields.form.max'),
            __rangeLabel: this.__('customFields.form.rangeLabel'),
            __allowOther: this.__('customFields.form.allowOther'),
            __properties: this.__('base.properties'),
            __or: this.__('base.or'),
            __slug: this.__('base.slug'),
            __globalSaveBtn: this.__('base.saveBtn'),
            __globalSaveAndCloseBtn: this.__('base.saveAndCloseBtn'),
            __globalSaveAndNewBtn: this.__('base.saveAndNewBtn'),
            __globalCancelBtn: this.__('base.cancelBtn'),
            __width: this.__('base.width'),
            __id: this.__('base.id'),
            __class: this.__('base.class'),
        };
    }
};